Feature/IIWA-37
kirbur/it-inventory pull request #4
Opened 2019-06-05 17:48 UTC by kirbur

Cards and Titles are made

2019-06-05 18:05 UTC, mtleonard120 commented on src/frontend-admin/src/components/reusables/Card/Card.tsx
> +    title: any
Nice, I agree this should be an `any`. That way we can pass in strings, components, whatever

2019-06-05 18:06 UTC, mtleonard120 commented on src/frontend-admin/src/components/reusables/Card/Card.tsx
> +    title: any
That said, this likely should be `title?: any`. That'll give us flexibility to have cards without titles if we ever need them.

2019-06-05 18:07 UTC, mtleonard120 commented on src/frontend-admin/src/components/reusables/Card/Card.tsx
> +            <Title title={title}/>
If our title prop is optional, you can change this line to be `{title && <Title title={title} />}` Conditional rendering like that is probably my favorite aspect of jsx :)

2019-06-05 18:08 UTC, mtleonard120 commented on src/frontend-admin/src/components/reusables/Card/Card.tsx
> +}
One other prop you may consider adding here (and really any widely reusable component) is an optional `className`. That way should we ever need to override any stylings when using a card we can easily do so. You can then use your classnames package to concatenate this optional prop with `styles.cardMain`.

2019-06-05 18:09 UTC, mtleonard120 requested changes
Just a couple small suggestions - looking good :)

2019-06-06 13:16 UTC, mcdowellalex approved these changes

2019-06-06 13:27 UTC, merged